// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqU_tEsK6VGRnKChiwv0ScmE7GHmlv9NE',
    appId: '1:273567794894:web:72c60c8a0f816520f6329f',
    messagingSenderId: '273567794894',
    projectId: 'salhub-cee08',
    authDomain: 'salhub-cee08.firebaseapp.com',
    storageBucket: 'salhub-cee08.firebasestorage.app',
    measurementId: 'G-E0EJLGQBQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2l_ZJxeGbRoNPA0h-WFPmkmfUi-rzN0',
    appId: '1:273567794894:android:a34ea96c505fc973f6329f',
    messagingSenderId: '273567794894',
    projectId: 'salhub-cee08',
    storageBucket: 'salhub-cee08.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Nj3FlNIjH8NGloyY8PJqXGoD_MSABfc',
    appId: '1:273567794894:ios:e04e2a330904d29bf6329f',
    messagingSenderId: '273567794894',
    projectId: 'salhub-cee08',
    storageBucket: 'salhub-cee08.firebasestorage.app',
    iosBundleId: 'com.example.salhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqU_tEsK6VGRnKChiwv0ScmE7GHmlv9NE',
    appId: '1:273567794894:web:2d13b0bd367f436ff6329f',
    messagingSenderId: '273567794894',
    projectId: 'salhub-cee08',
    authDomain: 'salhub-cee08.firebaseapp.com',
    storageBucket: 'salhub-cee08.firebasestorage.app',
    measurementId: 'G-RK5JJG272M',
  );
}
